In [1]:
import os
import numpy as np
import pandas as pd
import math
from matplotlib import pyplot as plt
import mne

In [2]:
annotations_a = r'A:\Sano\neonatal_data\annotations_2017_A_fixed.csv'
annotations_b = r'A:\Sano\neonatal_data\annotations_2017_B.csv'
annotations_c = r'A:\Sano\neonatal_data\annotations_2017_C.csv'

In [ ]:
annot_a = pd.read_csv(annotations_a).transpose().to_numpy()
annot_b = pd.read_csv(annotations_b).transpose().to_numpy()
annot_c = pd.read_csv(annotations_c).transpose().to_numpy()
unified_annot = np.empty((annot_a.shape[0],annot_a.shape[1]))
unified_annot[:] = np.NaN

In [ ]:
nan = np.NaN
patient_count = annot_a.shape[0]
second_count = annot_a.shape[1]
for n in range(0,patient_count): 
    for s in range (0,second_count):
        #print(annot_a[n][s])
        if (annot_a[n][s] == 1) and (annot_b[n][s] == 1)  and (annot_c[n][s] == 1):
            unified_annot[n][s] = 1
        elif  math.isnan(annot_a[n][s]) and math.isnan(annot_b[n][s]) and math.isnan(annot_c[n][s]):
            unified_annot[n][s] = nan
        else:
            unified_annot[n][s] = 0

In [ ]:
new_df = pd.DataFrame(unified_annot)
new_df.index +=1
save_df = new_df.transpose()

In [ ]:
save_df.to_csv(r'seizure_events\consensus_annotations.csv',index=False)

In [3]:
consensus_df = pd.read_csv(r'seizure_events\consensus_annotations.csv').transpose().to_numpy()

In [51]:
for n,patient in enumerate(consensus_df):
    no_nan_vals = np.expand_dims(patient[~np.isnan(patient)],axis=-1)
    timestep_array = np.expand_dims(np.arange(no_nan_vals.shape[0],step=1)*256,axis=-1)
    zero_col = np.expand_dims(np.zeros((no_nan_vals.shape[0])),axis=-1)
    event_array = np.concatenate((timestep_array,zero_col,no_nan_vals),axis=1).astype(np.int32)
    mne.write_events(fr"A:\Sano\seizure_events\events_per_patient\patient_{n+1}-eve.fif",event_array,overwrite=True)
        # np.save(fr"A:\Sano\new_annotations\events_annot\")
        # np.savetxt(fr"new_annotations\txt_annotations\annotations_patient_{n+1}.gz",no_nan_vals,fmt ='%.0f')
        # np.save(fr"new_annotations\npy_annotations\annotations_patient_{n+1}.npy",no_nan_vals)

In [52]:
for n,patient in enumerate(consensus_df):
    no_nan_vals = np.expand_dims(patient[~np.isnan(patient)],axis=-1)
    timestep_array = np.expand_dims(np.arange(no_nan_vals.shape[0],step=1),axis=-1)
    event_type = []
    for p, event in enumerate(no_nan_vals):
        if event[0] == 1:
            event_type.append('seizure')
        else:
            event_type.append('non_seizure')
    event_array = np.expand_dims(np.asarray(event_type),axis=-1)
    #indexes, _ = np.where(no_nan_vals == 1)
    event_annotations = np.concatenate((timestep_array,event_array,no_nan_vals),axis=1)
    annotated_df = pd.DataFrame(event_annotations,columns=['latency','type','position'])
    annotated_df.to_csv(rf"seizure_events\events_per_patient_eeglab\patient_{n+1}.csv",index=False)
    #np.savetxt(rf"A:\Sano\seizure_events\events_per_patient_eeglab\patient_{n+1}.txt",event_annotations)

In [53]:
np.load("A:\Sano\seizure_events\seizure_patients.npy")

array(['1', '4', '5', '7', '9', '11', '13', '14', '15', '16', '17', '19',
       '20', '21', '22', '25', '31', '34', '36', '38', '39', '40', '41',
       '44', '47', '50', '51', '52', '62', '63', '66', '67', '69', '73',
       '75', '76', '77', '78', '79'], dtype='<U2')

In [47]:
annotated_df = pd.DataFrame(event_annotations,columns=['Latency','Type','Position'])

In [48]:
annotated_df.to_csv("test.csv",index=False)

In [40]:
for item in event_annotations:
    print(item)

['0' 'non_seizure' '0.0']
['1' 'non_seizure' '0.0']
['2' 'non_seizure' '0.0']
['3' 'non_seizure' '0.0']
['4' 'non_seizure' '0.0']
['5' 'non_seizure' '0.0']
['6' 'non_seizure' '0.0']
['7' 'non_seizure' '0.0']
['8' 'non_seizure' '0.0']
['9' 'non_seizure' '0.0']
['10' 'non_seizure' '0.0']
['11' 'non_seizure' '0.0']
['12' 'non_seizure' '0.0']
['13' 'non_seizure' '0.0']
['14' 'non_seizure' '0.0']
['15' 'non_seizure' '0.0']
['16' 'non_seizure' '0.0']
['17' 'non_seizure' '0.0']
['18' 'non_seizure' '0.0']
['19' 'non_seizure' '0.0']
['20' 'non_seizure' '0.0']
['21' 'non_seizure' '0.0']
['22' 'non_seizure' '0.0']
['23' 'non_seizure' '0.0']
['24' 'non_seizure' '0.0']
['25' 'non_seizure' '0.0']
['26' 'non_seizure' '0.0']
['27' 'non_seizure' '0.0']
['28' 'non_seizure' '0.0']
['29' 'non_seizure' '0.0']
['30' 'non_seizure' '0.0']
['31' 'non_seizure' '0.0']
['32' 'non_seizure' '0.0']
['33' 'non_seizure' '0.0']
['34' 'non_seizure' '0.0']
['35' 'non_seizure' '0.0']
['36' 'non_seizure' '0.0']
['37' 'non_

In [10]:
first, second = np.where(no_nan_vals == 1)

In [ ]:
np.val

In [12]:
no_nan_vals[first]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [9]:
np.where(no_nan_vals == 1)

(array([ 149,  150,  151,  152,  153,  154,  155,  156,  157,  158,  159,
         160,  161,  162,  163,  164,  165,  166,  167,  168,  169,  170,
         171,  172,  173,  174,  175,  176,  177,  178,  179,  180,  181,
         182,  183,  184,  185,  186,  187,  188,  366,  367,  368,  369,
         370,  371,  372,  373,  374,  375,  376,  377,  378,  379,  380,
         381,  382,  565,  566,  567,  568,  569,  570,  571,  572,  573,
         574,  575,  576,  577,  578,  579,  580,  581,  582,  583,  584,
         585,  586,  587,  588,  589,  590,  591,  592,  593,  594,  595,
         596,  597,  598,  599,  600,  601,  602,  603,  604,  605,  606,
         607,  608,  609,  610,  611,  612,  613,  614,  615,  616,  617,
         618,  619, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151,
        2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2442,
        2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453,
        2454, 2455, 2456, 2457, 2458, 

In [7]:
print(timestep_array)

[[   0]
 [   1]
 [   2]
 ...
 [3294]
 [3295]
 [3296]]
